apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: seldon-mock-model
spec:
  annotations:
    seldon.io/executor: "true"
  name: mock-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: mock-model:latest
          name: mock-model
    graph:
      name: mock-model-1
      type: MODEL
      endpoint:
        type: REST
        service_host: 0.0.0.0
        service_port: 9000
      children:
      - name: mock-model-2
        type: MODEL
        endpoint:
          type: REST
          service_host: 0.0.0.0
          service_port: 9001
    name: example
    replicas: 1
